[platformio]
build_cache_dir = .pio/cache

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = espidf
board_build.flash_mode = dio

lib_deps = 
    lvgl/lvgl@^9.0.0

board_build.partitions = partitions_singleapp_large.csv

monitor_port = /dev/ttyACM0
monitor_speed = 115200

upload_protocol = esptool
upload_port = /dev/ttyACM0

debug_tool = esp-builtin
build_type = debug
debug_speed = 1000
debug_load_mode = manual
debug_init_break = thb app_main
build_flags = 
    -Wl,--undefined=uxTopUsedPriority